// lib/services/encryptionService.js
// Provides AES-256-GCM encryption for exchange API keys at rest

const crypto = require('crypto');

// Get the encryption secret from env. Ensure it's exactly 32 bytes for AES-256.
// If it's shorter/longer, we hash it via sha256 to guarantee 32 bytes.
const ENCRYPTION_SECRET = process.env.ENCRYPTION_SECRET || 'default_fallback_secret_do_not_use_in_prod';
const key = crypto.createHash('sha256').update(String(ENCRYPTION_SECRET)).digest('base64').substring(0, 32);

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 16;
const SALT_LENGTH = 64;

/**
 * Encrypts plaintext using AES-256-GCM.
 * Returns a base64 string containing: salt:iv:authTag:encryptedText
 */
function encrypt(text) {
  if (!text) return null;

  try {
    const iv = crypto.randomBytes(IV_LENGTH);
    const salt = crypto.randomBytes(SALT_LENGTH);
    
    // Key derivation (adds salt to the base key)
    const derivedKey = crypto.pbkdf2Sync(key, salt, 100000, 32, 'sha512');

    const cipher = crypto.createCipheriv(ALGORITHM, derivedKey, iv);
    
    let encrypted = cipher.update(text, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    
    const tag = cipher.getAuthTag();

    // Format: salt:iv:tag:ciphertext
    return Buffer.from(
      `${salt.toString('hex')}:${iv.toString('hex')}:${tag.toString('hex')}:${encrypted}`
    ).toString('base64');
  } catch (error) {
    console.error('Encryption failed:', error);
    throw new Error('Encryption failed');
  }
}

/**
 * Decrypts a base64 string generated by encrypt()
 */
function decrypt(encryptedBase64) {
  if (!encryptedBase64) return null;

  try {
    const text = Buffer.from(encryptedBase64, 'base64').toString('utf8');
    const parts = text.split(':');
    
    if (parts.length !== 4) {
      throw new Error('Invalid encryption payload format');
    }

    const salt = Buffer.from(parts[0], 'hex');
    const iv = Buffer.from(parts[1], 'hex');
    const tag = Buffer.from(parts[2], 'hex');
    const encrypted = parts[3];

    const derivedKey = crypto.pbkdf2Sync(key, salt, 100000, 32, 'sha512');

    const decipher = crypto.createDecipheriv(ALGORITHM, derivedKey, iv);
    decipher.setAuthTag(tag);
    
    let decrypted = decipher.update(encrypted, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    
    return decrypted;
  } catch (error) {
    console.error('Decryption failed:', error);
    throw new Error('Decryption failed');
  }
}

module.exports = {
  encrypt,
  decrypt
};
